version: '3.8'
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: sa_appointment
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5433"
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d sa_appointment"]
      interval: 3s
      timeout: 2s
      retries: 20

  sa_appointment:
    image: sa_appointment:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_PORT=5433
    ports:
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_healthy

networks:
  default:
    driver: bridge

